### ISSUE TITLE
Last version of libmlx.a causes "warning: size of symbol `mlx_int_param_event' changed" issue with program made with the previous version.

### ISSUE THREAD

**Issue by lrcouto** [42Paris/minilibx-linux#24]
Running a MiniRT project with the newest version of minilibx-linux, I encountered the following problem when compiling:

``` /usr/bin/ld: warning: size of symbol `mlx_int_param_event' changed from 296 in objs/main/init_rt.o to 288 in /usr/local/lib/libmlx.a(mlx_int_param_event.o ```

After that, any function using the mlx int parameters stops working i.e. can't close windows by clicking the "x" buttons, the program simply ignores any function that calls these parameters. This behavior happens even on the mlx tester program.

The problem was solved by using a libmlx.a file compiled from the august release instead of the late november one.

**Comment by lrcouto** [comment]
System specifications:

Ubuntu 20.04.1
GNU Binutils 2.34
GCC 9.3.0
GNU Make 4.2.1

Tested on another computer using exactly the same specs but without the most recent version of MiniLibX, which worked.

**Comment by Salty42** [comment]
Hi,
Tnaks for your issues, we will rollback
