### ISSUE TITLE
Pull #22 Introduced issue with exit on red cross

### ISSUE THREAD

**Issue by michaelgiraldo** [42Paris/minilibx-linux#25]
https://github.com/42Paris/minilibx-linux/pull/22

This has change has fundamental changed behavior of lot of existing code. mlx_destroy_window was working just fine. Now, minilibx is not recognizing mask & event for exiting on red cross.

@lsoulier42 @adhanot @alexandregv

Pull 22, should be reverted and further testing should be performed

**Comment by lsoulier42** [comment]
The students who are doing this project atm use this version and seem perfectly happy that they don't have to use a different function to exit with escape and red cross, which was made possible with the last fix, so I wouldn't recommend to revert this PR.
Instead, maybe you can change your own code to make it work with the new version, all you have to do is using event 33 (and not 17 which is the event for exiting on macos).
