### ISSUE TITLE
ubuntu 22.04 

### ISSUE THREAD

**Issue by NajmiAchraf** [42Paris/minilibx-linux#47]
./configure
configure [error] : Can't find a suitable X11 include directory.
make: *** [Makefile:17: do_configure] Error 1

**Comment by N0ViP** [comment]
You should install the required X11 development packages:

$ sudo apt install libx11-dev libxext-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev
$ sudo apt install xorg-dev

then make
